### ISSUE TITLE
[Fix] ranking 관리를 위한 entity 수정 및 유저 정보 조회 기능 수정

### ISSUE THREAD

**Issue by S4NGP1L** [ChickenStock-2024/BackEnd#21]
### 📄 Describe
전체 랭킹, 라이벌 랭킹 조회를 하기 쉽게 entity 구조를 변경합니다.

### ✅ Tasks
- [x] Rating Entity 삭제
- [x] Account Entity 수정
- [ ] Member Entity 수정
- [x] 유저 정보 조회 기능 수정

**Comment by S4NGP1L** [comment]
close #21
