### ISSUE TITLE
[Feat] 유저의 전체랭킹 조회 기능 구현

### ISSUE THREAD

**Issue by S4NGP1L** [ChickenStock-2024/BackEnd#23]
### 📄 Describe
레이팅 기반으로 전체 랭킹을 구하는 기능을 구현합니다.
추가로 레이팅 계산기도 구현합니다.

### ✅ Tasks
- [x] 유저의 랭킹 조회 기능 구현
- [x] 유저의 등수 조회하는 요청에 해당 기능 추가
- [ ] 레이팅 계산기 구현
