### ISSUE TITLE
[Feat] 주식 매수, 매도 구현

### ISSUE THREAD

**Issue by KLJH1025** [ChickenStock-2024/BackEnd#28]
### 📄 Describe

주식 매수, 매도에 따른 개인 주식 보유 현황과 계좌의 잔고 관리를 구현할 예정입니다.

### ✅ Tasks
- [ ] 지정가 매수 요청 기능 구현
- [ ] 시장가 매수 요청 기능 구현
- [ ] 지정가 매도 요청 기능 구현
- [ ] 시장가 매도 요청 기능 구현

- [ ] 매수 성공시, 계좌 잔고 금액 차감 구현
- [ ] 매수 성공시, 개인 보유 주식에 구매한 주식 추가
- [ ] 매도 성공시, 계좌 잔고 금액 증가 구현
- [ ] 매도 성공시, 개인 보유 주식에서 판매한 주식 제거

- [ ] 조건에 맞지 않은 주문 예외처리. (금액 부족 등등..)
