### ISSUE TITLE
[Feat] 주식 목록 조회 구현

### ISSUE THREAD

**Issue by KLJH1025** [ChickenStock-2024/BackEnd#76]
### 📄 Describe

주식 목록 조회 구현

### ✅ Tasks

- [ ] Company 테이블에 있는 회사들을 읽고 전체 주식 종목 리스트 반환
- [ ] 검색 텍스트필드에 있는 문자열을 포함하는 주식 종목 리스트 반환
- [ ] 주식 종목 클릭시 해당 주식 데이터 차트에 띄우는 로직 구현
