### ISSUE TITLE
[Fix] 체결 내역 조회 기능 Redis key 수정, 미체결내역 기능 개발

### ISSUE THREAD

**Issue by namesnames** [ChickenStock-2024/BackEnd#87]
### 📄 Describe
[Fix] 체결 내역 조회 기능 Redis key 수정

### ✅ Tasks
- [x] [체결 내역 조회 기능 Redis key 수정
- [x] 요청온 것 Redis에 "미체결내역" 추가
- [x] "요청취소"가 오면 historyId로 찾아서 "미체결내역"에서 삭제
- [x] "memberId"에 해당하는 모든 "미체결내역" 반환해주기
